name: PocketGameCore
version: 0.2
main: Core\Main
api: [3.0.0]
author: MTwins
permissions:
  lobby.yt:
    default: op
commands:
  hub:
     description: hub
     usage: /hub
  lobby:
     description: lobby
     usage: /lobby
